- name: Install multimedia softwares using snap
  snap: name={{ item }} state=present
  loop: ['obs-studio', 'vlc', 'gimp']
  
- name: Install multimedia softwares using apt
  apt: name={{ item }} state=present
  loop: ['cheese']
