- name: Install WPS office
  apt:
    deb: http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/9615/wps-office_11.1.0.9615.XA_amd64.deb

- name: Install office tools
  snap: name={{ item }} state=present classic=yes
  loop: ['libreoffice']
