- name: Install development tools with option --classic
  snap: name={{ item }} state=present classic=yes
  loop: ['pycharm-professional', 'microk8s', 'heroku', 'code', 'clion']

- name: Install development tools
  snap: name={{ item }} state=present
  loop: ['dbeaver-ce', 'postman', 'poedit']

- name: Install development tools and libraries with apt
  apt: name={{ item }} state=present
  loop: ['vim', 'meld', 'make', 'build-essential', 'libssl-dev', 'zlib1g-dev', 'libbz2-dev', 'libreadline-dev', 'libsqlite3-dev', 'wget', 'curl', 'llvm', 'libncurses5-dev', 'xz-utils', 'tk-dev', 'libxml2-dev', 'libxmlsec1-dev', 'libffi-dev', 'liblzma-dev', 'libcurl4-openssl-dev', 'libpq-dev', 'libusb-dev', 'jq', 'autoconf', 'automake', 'xsltproc', 'fop']

- name: Add Github CLI GPG apt Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C99B11DEB97541F0

- name: Add Github CLI Repository
  apt_repository:
    repo: deb https://cli.github.com/packages groovy main
    state: present

- name: Install Github CLI
  apt:
    update_cache: yes
    name: gh
    state: present
