- apt_repository:
    repo: ppa:regolith-linux/release

- name: Install regolith-desktop
  apt: update_cache=yes name={{ item }} state=latest
  loop: ['regolith-desktop', 'i3xrocks-net-traffic', 'i3xrocks-cpu-usage', 'i3xrocks-time', 'i3xrocks-battery', 'i3blocks', 'gnome-tweaks', 'gnome-screensaver', 'dconf-editor', 'xcwd']

- name: Install python modules for bumblebee-status
  pip:
    name: bublebee-status pygit2 netifaces

