- name: Add peek GPG apt Key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=hget&search=eedf7ede39b41e8eecdcf7832b959b4c
    state: present

- name: Add peek Repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/peek-developers/stable/ubuntu focal main
    state: present

- name: Add Terraform GPG apt Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Terraform Repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com groovy main
    state: present

- name: Install tools
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['htop', 'wireshark', 'peek', 'flameshot', 'rsync', 'iotop', 'graphviz', 'gnome-software-plugin-flatpak', 'p7zip', 'tree', 'terraform', 'bsdmainutils']

- name: Download virtualbox 6.1_6.1.12-139181
  get_url:
    url: https://download.virtualbox.org/virtualbox/6.1.12/virtualbox-6.1_6.1.12-139181~Ubuntu~eoan_amd64.deb
    dest: /tmp/virtualbox.deb

- name: Install virtualbox 6.1_6.1.12-139181
  apt:
    deb: /tmp/virtualbox.deb

- name: Install konsole
  apt:
    name: konsole
