- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker stack
  apt: update_cache=yes name={{ item }} state=present
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Install docker-machine
  get_url:
    url: https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-linux-x86_64
    dest: /usr/local/bin/docker-machine
    group: docker
    mode: 'u=rx,g=rx'
